"""
This type stub file was generated by pyright.
"""

from typing import BinaryIO, Union

"""We use the PyAV library to decode the audio: https://github.com/PyAV-Org/PyAV

The advantage of PyAV is that it bundles the FFmpeg libraries so there is no additional
system dependencies. FFmpeg does not need to be installed on the system.

However, the API is quite low-level so we need to manipulate audio frames directly.
"""
def decode_audio(input_file: Union[str, BinaryIO], sampling_rate: int = ..., split_stereo: bool = ...): # -> tuple[ndarray[_Shape, dtype[floating[Any]]], ndarray[_Shape, dtype[floating[Any]]]] | NDArray[floating[Any]]:
    """Decodes the audio.

    Args:
      input_file: Path to the input file or a file-like object.
      sampling_rate: Resample the audio to this sample rate.
      split_stereo: Return separate left and right channels.

    Returns:
      A float32 Numpy array.

      If `split_stereo` is enabled, the function returns a 2-tuple with the
      separated left and right channels.
    """
    ...

def pad_or_trim(array, length: int = ..., *, axis: int = ...): # -> NDArray[Any]:
    """
    Pad or trim the Mel features array to 3000, as expected by the encoder.
    """
    ...

