"""
This type stub file was generated by pyright.
"""

import numpy as np

class FeatureExtractor:
    def __init__(self, feature_size=..., sampling_rate=..., hop_length=..., chunk_length=..., n_fft=...) -> None:
        ...
    
    @staticmethod
    def get_mel_filters(sr, n_fft, n_mels=...): # -> Any:
        ...
    
    @staticmethod
    def stft(input_array: np.ndarray, n_fft: int, hop_length: int = ..., win_length: int = ..., window: np.ndarray = ..., center: bool = ..., mode: str = ..., normalized: bool = ..., onesided: bool = ..., return_complex: bool = ...): # -> ndarray[_Shape, dtype[complex128]] | ndarray[_Shape, dtype[float64]]:
        ...
    
    def __call__(self, waveform: np.ndarray, padding=..., chunk_length=...): # -> Any:
        """
        Compute the log-Mel spectrogram of the provided audio.
        """
        ...
    


