"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Union
from tqdm.auto import tqdm

_MODELS = ...
def available_models() -> List[str]:
    """Returns the names of available models."""
    ...

def get_assets_path(): # -> str:
    """Returns the path to the assets directory."""
    ...

def get_logger(): # -> Logger:
    """Returns the module logger."""
    ...

def download_model(size_or_id: str, output_dir: Optional[str] = ..., local_files_only: bool = ..., cache_dir: Optional[str] = ..., revision: Optional[str] = ..., use_auth_token: Optional[Union[str, bool]] = ...):
    """Downloads a CTranslate2 Whisper model from the Hugging Face Hub.

    Args:
      size_or_id: Size of the model to download from https://huggingface.co/Systran
        (tiny, tiny.en, base, base.en, small, small.en, distil-small.en, medium, medium.en,
        distil-medium.en, large-v1, large-v2, large-v3, large, distil-large-v2,
        distil-large-v3), or a CTranslate2-converted model ID from the Hugging Face Hub
        (e.g. Systran/faster-whisper-large-v3).
      output_dir: Directory where the model should be saved. If not set, the model is saved in
        the cache directory.
      local_files_only:  If True, avoid downloading the file and return the path to the local
        cached file if it exists.
      cache_dir: Path to the folder where cached files are stored.
      revision: An optional Git revision id which can be a branch name, a tag, or a
            commit hash.
      use_auth_token: HuggingFace authentication token or True to use the
            token stored by the HuggingFace config folder.

    Returns:
      The path to the downloaded model.

    Raises:
      ValueError: if the model size is invalid.
    """
    ...

def format_timestamp(seconds: float, always_include_hours: bool = ..., decimal_marker: str = ...) -> str:
    ...

class disabled_tqdm(tqdm):
    def __init__(self, *args, **kwargs) -> None:
        ...
    


def get_end(segments: List[dict]) -> Optional[float]:
    ...

