"""
This type stub file was generated by pyright.
"""

from typing import Optional
from ctranslate2.converters.converter import Converter

_SUPPORTED_MODELS = ...
_SUPPORTED_ACTIVATIONS = ...
class FairseqConverter(Converter):
    """Converts models trained with Fairseq."""
    def __init__(self, model_path: str, data_dir: str, source_lang: Optional[str] = ..., target_lang: Optional[str] = ..., fixed_dictionary: Optional[str] = ..., no_default_special_tokens: bool = ..., user_dir: Optional[str] = ...) -> None:
        """Initializes the Fairseq converter.

        Arguments:
          model_path: Path to the Fairseq PyTorch model (.pt file).
          data_dir: Path to the Fairseq data directory containing vocabulary files.
          source_lang: Source language (may be required if not declared in the model).
          target_lang: Target language (may be required if not declared in the model).
          fixed_dictionary: Path to the fixed dictionary for multilingual models.
          no_default_special_tokens: Require all special tokens to be provided by the user
            (e.g. encoder end token, decoder start token).
          user_dir: Path to the user directory containing custom extensions.
        """
        ...
    


def set_transformer_encoder(spec, module): # -> None:
    ...

def set_transformer_decoder(spec, module, with_encoder_attention=...): # -> None:
    ...

def set_input_layers(spec, module): # -> None:
    ...

def set_transformer_encoder_layer(spec, module): # -> None:
    ...

def set_transformer_decoder_layer(spec, module, with_encoder_attention=...): # -> None:
    ...

def set_ffn(spec, module): # -> None:
    ...

def set_multi_head_attention(spec, module, self_attention=...): # -> None:
    ...

def set_layer_norm(spec, module): # -> None:
    ...

def set_linear(spec, module): # -> None:
    ...

def set_embeddings(spec, module): # -> None:
    ...

def set_position_encodings(spec, module): # -> None:
    ...

def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
