"""
This type stub file was generated by pyright.
"""

from typing import List
from ctranslate2.converters.converter import Converter

_SUPPORTED_ACTIVATIONS = ...
_SUPPORTED_POSTPROCESS_EMB = ...
class MarianConverter(Converter):
    """Converts models trained with Marian."""
    def __init__(self, model_path: str, vocab_paths: List[str]) -> None:
        """Initializes the Marian converter.

        Arguments:
          model_path: Path to the Marian model (.npz file).
          vocab_paths: Paths to the vocabularies (.yml files).
        """
        ...
    


def load_vocab(path): # -> list[Any]:
    ...

def set_transformer_spec(spec, weights): # -> None:
    ...

def set_transformer_encoder(spec, weights, scope): # -> None:
    ...

def set_transformer_decoder(spec, weights, scope): # -> None:
    ...

def set_common_layers(spec, weights, scope): # -> None:
    ...

def set_transformer_encoder_layer(spec, weights, scope): # -> None:
    ...

def set_transformer_decoder_layer(spec, weights, scope): # -> None:
    ...

def set_multi_head_attention(spec, weights, scope, self_attention=...): # -> None:
    ...

def set_ffn(spec, weights, scope): # -> None:
    ...

def set_layer_norm_auto(spec, weights, scope): # -> None:
    ...

def set_layer_norm(spec, weights, scope, pre_norm=...): # -> None:
    ...

def set_linear(spec, weights, scope, suffix=..., reuse_weight=...): # -> None:
    ...

def set_embeddings(spec, weights, scope): # -> None:
    ...

def set_position_encodings(spec, weights, dim=...): # -> None:
    ...

def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
