"""
This type stub file was generated by pyright.
"""

from ctranslate2.converters.converter import Converter

_SUPPORTED_ACTIVATIONS = ...
_SUPPORTED_FEATURES_MERGE = ...
def check_opt(opt, num_source_embeddings): # -> None:
    ...

def get_vocabs(vocab): # -> tuple[list[list[Any]] | list[Any], list[Any]]:
    ...

class OpenNMTPyConverter(Converter):
    """Converts models generated by OpenNMT-py."""
    def __init__(self, model_path: str) -> None:
        """Initializes the OpenNMT-py converter.

        Arguments:
          model_path: Path to the OpenNMT-py PyTorch model (.pt file).
        """
        ...
    


def set_transformer_spec(spec, variables): # -> None:
    ...

def set_transformer_encoder(spec, variables): # -> None:
    ...

def set_transformer_decoder(spec, variables, with_encoder_attention=...): # -> None:
    ...

def set_input_layers(spec, variables, scope): # -> None:
    ...

def set_transformer_encoder_layer(spec, variables, scope): # -> None:
    ...

def set_transformer_decoder_layer(spec, variables, scope, with_encoder_attention=...): # -> None:
    ...

def set_ffn(spec, variables, scope): # -> None:
    ...

def set_multi_head_attention(spec, variables, scope, self_attention=...): # -> None:
    ...

def set_layer_norm(spec, variables, scope): # -> None:
    ...

def set_linear(spec, variables, scope): # -> None:
    ...

def set_embeddings(spec, variables, scope): # -> None:
    ...

def set_position_encodings(spec, variables, scope): # -> None:
    ...

def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
