"""
This type stub file was generated by pyright.
"""

from ctranslate2.converters.converter import Converter

class OpenAIGPT2Converter(Converter):
    """Converts GPT-2 models from https://github.com/openai/gpt-2."""
    def __init__(self, model_dir: str) -> None:
        """Initializes the OpenAI GPT-2 converter.

        Arguments:
          model_dir: Path to the OpenAI GPT-2 model directory.
        """
        ...
    


def set_decoder(spec, weights, scope): # -> None:
    ...

def set_layer_norm(spec, weights, scope): # -> None:
    ...

def set_linear(spec, weights, scope): # -> None:
    ...

def set_layer(spec, weights, scope): # -> None:
    ...

def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
