"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from ctranslate2.converters.converter import Converter

_SUPPORTED_ACTIVATIONS = ...
class OpenNMTTFConverter(Converter):
    """Converts OpenNMT-tf models."""
    @classmethod
    def from_config(cls, config: Union[str, dict], auto_config: bool = ..., checkpoint_path: Optional[str] = ..., model: Optional[str] = ...): # -> Self:
        """Creates the converter from the configuration.

        Arguments:
          config: Path to the YAML configuration, or a dictionary with the loaded configuration.
          auto_config: Whether the model automatic configuration values should be used.
          checkpoint_path: Path to the checkpoint or checkpoint directory to load. If not set,
            the latest checkpoint from the model directory is loaded.
          model: If the model instance cannot be resolved from the model directory, this argument
             can be set to either the name of the model in the catalog or the path to the model
             configuration.

        Returns:
          A :class:`ctranslate2.converters.OpenNMTTFConverter` instance.
        """
        ...
    
    def __init__(self, model) -> None:
        """Initializes the converter.

        Arguments:
          model: An initialized and fully-built ``opennmt.models.Model`` instance.
        """
        ...
    


class TransformerSpecBuilder:
    def __call__(self, model): # -> TransformerSpec:
        ...
    
    def set_transformer_encoder(self, spec, module, inputter): # -> None:
        ...
    
    def set_transformer_decoder(self, spec, module, inputter): # -> None:
        ...
    
    def set_ffn(self, spec, module): # -> None:
        ...
    
    def set_multi_head_attention(self, spec, module, self_attention=...): # -> None:
        ...
    
    def set_layer_norm_from_wrapper(self, spec, module): # -> None:
        ...
    
    def set_layer_norm(self, spec, module): # -> None:
        ...
    
    def set_linear(self, spec, module): # -> None:
        ...
    
    def set_embeddings(self, spec, module): # -> None:
        ...
    
    def set_position_encodings(self, spec, module): # -> None:
        ...
    


class TransformerDecoderSpecBuilder(TransformerSpecBuilder):
    def __call__(self, model): # -> TransformerDecoderModelSpec:
        ...
    


def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
