"""
This type stub file was generated by pyright.
"""

from ctranslate2.converters.marian import MarianConverter

class OpusMTConverter(MarianConverter):
    """Converts models trained with OPUS-MT."""
    def __init__(self, model_dir: str) -> None:
        """Initializes the OPUS-MT converter.

        Arguments:
          model_dir: Path the OPUS-MT model directory.
        """
        ...
    


def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
