"""
This type stub file was generated by pyright.
"""

import abc
from typing import List, Optional
from ctranslate2.converters.converter import Converter

_SUPPORTED_ACTIVATIONS = ...
_SUPPORTED_ROPE_SCALING = ...
_SUPPORTED_QUANTIZATION = ...
_MODEL_LOADERS = ...
def register_loader(config_name): # -> Callable[..., Any]:
    """Registers a model loader for this configuration name."""
    ...

class TransformersConverter(Converter):
    """Converts models from Hugging Face Transformers."""
    def __init__(self, model_name_or_path: str, activation_scales: Optional[str] = ..., copy_files: Optional[List[str]] = ..., load_as_float16: bool = ..., revision: Optional[str] = ..., low_cpu_mem_usage: bool = ..., trust_remote_code: bool = ...) -> None:
        """Initializes the converter.

        Arguments:
          model_name_or_path: Name of the pretrained model to download, or path to the
            directory containing the pretrained model.
          activation_scales: Path to the pre-computed activation scales. Models may
            use them to rescale some weights to smooth the intermediate activations
            and improve the quantization accuracy. See
            https://github.com/mit-han-lab/smoothquant.
          copy_files: List of filenames to copy from the Hugging Face model to the
            converted model directory.
          load_as_float16: Load the model weights as float16. More precisely, the model
            will be loaded with ``from_pretrained(..., dtype=torch.float16)``.
          revision: Revision of the model to download from the Hugging Face Hub.
          low_cpu_mem_usage: Enable the flag ``low_cpu_mem_usage`` when loading the model
            with ``from_pretrained``.
          trust_remote_code: Allow converting models using custom code.
        """
        ...
    
    def load_model(self, model_class, model_name_or_path, **kwargs):
        ...
    
    def load_tokenizer(self, tokenizer_class, model_name_or_path, **kwargs):
        ...
    
    def get_model_file(self, filename): # -> str:
        ...
    


class ModelLoader(abc.ABC):
    """Base class for loading Transformers models into a CTranslate2 model specification."""
    @property
    def architecture_name(self): # -> None:
        ...
    
    @abc.abstractmethod
    def get_model_spec(self, model):
        ...
    
    def __call__(self, model, tokenizer):
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_layer_norm(self, spec, module): # -> None:
        ...
    
    def set_linear(self, spec, module, quant_type=...): # -> None:
        ...
    
    def set_embeddings(self, spec, module): # -> None:
        ...
    
    def set_position_encodings(self, spec, module): # -> None:
        ...
    
    def smooth_activation(self, spec, activation_scales):
        ...
    
    def get_rotary_params(self, config, default_rope_theta): # -> tuple[RotaryScalingType | None, Any | Literal[1], Any]:
        ...
    


@register_loader("BartConfig")
class BartLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['BartForConditionalGeneration']:
        ...
    
    def get_model_spec(self, model): # -> TransformerSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_encoder(self, spec, encoder): # -> None:
        ...
    
    def set_decoder(self, spec, decoder): # -> None:
        ...
    
    def set_attention(self, spec, attention, self_attention=...): # -> None:
        ...
    
    def set_common_layers(self, spec, module): # -> None:
        ...
    


@register_loader("MarianConfig")
class MarianMTLoader(BartLoader):
    @property
    def architecture_name(self): # -> Literal['MarianMTModel']:
        ...
    
    def get_model_spec(self, model): # -> TransformerSpec:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_decoder(self, spec, decoder): # -> None:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    


@register_loader("M2M100Config")
class M2M100Loader(BartLoader):
    @property
    def architecture_name(self): # -> Literal['M2M100ForConditionalGeneration']:
        ...
    
    def get_model_spec(self, model): # -> TransformerSpec:
        ...
    
    def set_position_encodings(self, spec, module): # -> None:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    


@register_loader("MBartConfig")
class MBartLoader(BartLoader):
    @property
    def architecture_name(self): # -> Literal['MBartForConditionalGeneration']:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    


@register_loader("PegasusConfig")
class PegasusLoader(BartLoader):
    @property
    def architecture_name(self): # -> Literal['PegasusForConditionalGeneration']:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    


@register_loader("OPTConfig")
class OPTLoader(BartLoader):
    @property
    def architecture_name(self): # -> Literal['OPTForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def smooth_activation(self, spec, activation_scales): # -> None:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_decoder(self, spec, decoder): # -> None:
        ...
    
    def set_common_layers(self, spec, module): # -> None:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    


@register_loader("GPTBigCodeConfig")
class GPTBigCodeMHALoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['GPTBigCodeForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_decoder(self, spec, module): # -> None:
        ...
    


@register_loader("GPT2Config")
class GPT2Loader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['GPT2LMHeadModel']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_decoder(self, spec, module): # -> None:
        ...
    


@register_loader("GPTJConfig")
class GPTJLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['GPTJForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_decoder(self, spec, module, rotary_dim, num_heads): # -> None:
        ...
    


@register_loader("CodeGenConfig")
class CodeGenLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['CodeGenForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_decoder(self, spec, module, rotary_dim, num_heads, embed_dim, mp_num): # -> None:
        ...
    


@register_loader("GPTNeoXConfig")
class GPTNeoXLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['GPTNeoXForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_decoder(self, spec, module, num_heads): # -> None:
        ...
    


@register_loader("WhisperConfig")
class WhisperLoader(BartLoader):
    @property
    def architecture_name(self): # -> Literal['WhisperForConditionalGeneration']:
        ...
    
    def get_model_spec(self, model): # -> WhisperSpec:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_encoder(self, spec, encoder): # -> None:
        ...
    
    def set_decoder(self, spec, decoder): # -> None:
        ...
    
    def set_common_layers(self, spec, module): # -> None:
        ...
    
    def set_conv1d(self, spec, module): # -> None:
        ...
    


@register_loader("Wav2Vec2Config")
class Wav2Vec2Loader(BartLoader):
    @property
    def architecture_name(self): # -> Literal['Wav2Vec2ForCTC']:
        ...
    
    def get_model_spec(self, model): # -> Wav2Vec2Spec:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def get_vocabulary(self, model, tokenizer):
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_feature_extractor(self, spec, feature_extractor): # -> None:
        ...
    
    def set_feature_projection(self, spec, feature_projection): # -> None:
        ...
    
    def set_pos_conv_embed(self, spec, encoder, config): # -> None:
        ...
    
    def set_encoder(self, spec, model, config): # -> None:
        ...
    
    def set_common_layers(self, spec, module): # -> None:
        ...
    


@register_loader("Wav2Vec2BertConfig")
class Wav2Vec2BertLoader(BartLoader):
    @property
    def architecture_name(self): # -> Literal['Wav2Vec2BertForCTC']:
        ...
    
    def get_model_spec(self, model): # -> Wav2Vec2BertSpec:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def get_vocabulary(self, model, tokenizer):
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_feature_projection(self, spec, feature_projection): # -> None:
        ...
    
    def set_attention(self, spec, attention, left_max_position=..., right_max_position=...): # -> None:
        ...
    
    def set_wav2vec2bert_encoder(self, spec_layers, layers, left_max_position, right_max_position): # -> None:
        ...
    
    def set_wav2vec2bert_adapter(self, spec_layers, layers): # -> None:
        ...
    
    def set_encoder(self, spec, model): # -> None:
        ...
    
    def set_conv1d(self, spec, module): # -> None:
        ...
    
    def set_layer_norm(self, spec, module): # -> None:
        ...
    


@register_loader("T5Config")
class T5Loader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['T5ForConditionalGeneration']:
        ...
    
    def get_model_spec(self, model): # -> TransformerSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_stack(self, spec, module, is_decoder=...): # -> None:
        ...
    
    def set_ffn(self, spec, module): # -> None:
        ...
    
    def set_self_attention(self, spec, module): # -> None:
        ...
    
    def set_cross_attention(self, spec, module): # -> None:
        ...
    
    def set_attention(self, spec, attention, self_attention=...): # -> None:
        ...
    
    def set_layer_norm(self, spec, layer_norm): # -> None:
        ...
    


@register_loader("MT5Config")
class MT5Loader(T5Loader):
    @property
    def architecture_name(self): # -> Literal['MT5ForConditionalGeneration']:
        ...
    


@register_loader("BloomConfig")
class BloomLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['BloomForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_decoder(self, spec, module): # -> None:
        ...
    
    def set_qkv_linear(self, spec, module, num_heads): # -> None:
        ...
    


@register_loader("MPTConfig")
class MPTLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['AutoModelForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_decoder(self, spec, module): # -> None:
        ...
    
    def set_layer_norm(self, spec, module): # -> None:
        ...
    


@register_loader("GemmaConfig")
class GemmaLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['GemmaForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_layer_norm(self, spec, layer_norm): # -> None:
        ...
    
    def set_decoder(self, spec, module): # -> None:
        ...
    


@register_loader("Gemma2Config")
class Gemma2Loader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['Gemma2ForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_layer_norm(self, spec, layer_norm): # -> None:
        ...
    
    def set_decoder(self, spec, module): # -> None:
        ...
    


@register_loader("LlamaConfig")
class LlamaLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['LlamaForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_layer_norm(self, spec, layer_norm): # -> None:
        ...
    
    def set_decoder(self, spec, module, quant_type=...): # -> None:
        ...
    


@register_loader("Gemma3TextConfig")
@register_loader("Gemma3Config")
class Gemma3Loader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['Gemma3ForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_layer_norm(self, spec, layer_norm): # -> None:
        ...
    
    def set_decoder(self, spec, module, quant_type=...): # -> None:
        ...
    


@register_loader("MistralConfig")
class MistralLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['MistralForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_layer_norm(self, spec, layer_norm): # -> None:
        ...
    
    def set_decoder(self, spec, module, quant_type=...): # -> None:
        ...
    


@register_loader("Qwen2Config")
class Qwen2Loader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['Qwen2ForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_layer_norm(self, spec, layer_norm): # -> None:
        ...
    
    def set_decoder(self, spec, module, quant_type=...): # -> None:
        ...
    


@register_loader("Qwen3Config")
class Qwen3Loader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['Qwen3ForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_layer_norm(self, spec, layer_norm): # -> None:
        ...
    
    def set_decoder(self, spec, module, quant_type=...): # -> None:
        ...
    


@register_loader("MixFormerSequentialConfig")
class MixFormerSequentialLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['AutoModelForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_decoder(self, spec, module): # -> None:
        ...
    


@register_loader("PhiConfig")
class PhiLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['AutoModelForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_decoder(self, spec, module): # -> None:
        ...
    


@register_loader("Phi3Config")
class Phi3Loader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['AutoModelForCausalLM']:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_layer_norm(self, spec, layer_norm): # -> None:
        ...
    
    def set_rotary_embeddings(self, spec, rotary_scaling_long_factor, rotary_scaling_short_factor): # -> None:
        ...
    
    def set_decoder(self, spec, module, quant_type=...): # -> None:
        ...
    


@register_loader("RWConfig")
class RWLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['AutoModelForCausalLM']:
        ...
    
    def get_falcon_spec(self, model): # -> None:
        ...
    
    def get_model_spec(self, model): # -> TransformerDecoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_decoder(self, spec, module): # -> None:
        ...
    
    def set_qkv_linear(self, spec, module, num_heads, num_kv=...): # -> None:
        ...
    


@register_loader("FalconConfig")
class FalconLoader(RWLoader):
    def get_falcon_spec(self, model): # -> None:
        ...
    


@register_loader("DistilBertConfig")
class DistilBertLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['DistilBertModel']:
        ...
    
    def get_model_spec(self, model): # -> TransformerEncoderModelSpec:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    


@register_loader("BertConfig")
class BertLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['BertModel']:
        ...
    
    def get_model_spec(self, model): # -> TransformerEncoderModelSpec:
        ...
    
    def get_vocabulary(self, model, tokenizer): # -> list[Any]:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    


@register_loader("XLMRobertaConfig")
class XLMRobertaLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['XLMRobertaForSequenceClassification']:
        ...
    
    def get_model_spec(self, model): # -> TransformerEncoderModelSpec:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_position_encodings(self, spec, module): # -> None:
        ...
    


@register_loader("RobertaConfig")
class RobertaLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['RobertaModel']:
        ...
    
    def get_model_spec(self, model): # -> TransformerEncoderModelSpec:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_position_encodings(self, spec, module): # -> None:
        ...
    


@register_loader("CamembertConfig")
class CamembertLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['CamembertModel']:
        ...
    
    def get_model_spec(self, model): # -> TransformerEncoderModelSpec:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_position_encodings(self, spec, module): # -> None:
        ...
    


def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
_WHISPER_ALIGNMENT_HEADS = ...
@register_loader("T5GemmaConfig")
class T5GemmaLoader(ModelLoader):
    @property
    def architecture_name(self): # -> Literal['T5GemmaForConditionalGeneration']:
        ...
    
    def set_layer_norm(self, spec, layer_norm): # -> None:
        ...
    
    def get_model_spec(self, model): # -> TransformerSpec:
        ...
    
    def set_vocabulary(self, spec, tokens): # -> None:
        ...
    
    def set_config(self, config, model, tokenizer): # -> None:
        ...
    
    def set_encoder(self, spec, encoder, encoder_config, quant_type=...): # -> None:
        ...
    
    def set_decoder(self, spec, module, decoder_config, quant_type=...): # -> None:
        ...
    


