"""
This type stub file was generated by pyright.
"""

def fuse_linear(spec, layers): # -> None:
    ...

def fuse_linear_prequant(spec, layers, axis): # -> None:
    ...

def permute_for_sliced_rotary(weight, num_heads, rotary_dim=...):
    """Permutes the weight to use the sliced rotary implementation."""
    ...

def smooth_activation(layer_norm, linear, activation_scales): # -> None:
    """Applies the activation smoothing technique described in
    https://github.com/mit-han-lab/smoothquant.
    """
    ...

def raise_unsupported(reasons):
    ...

class ConfigurationChecker:
    def __init__(self) -> None:
        ...
    
    def __call__(self, assert_condition, error_message): # -> None:
        ...
    
    def validate(self): # -> None:
        ...
    


