"""
This type stub file was generated by pyright.
"""

import enum
from ctranslate2.specs import model_spec

class RotaryScalingType(enum.IntEnum):
    """RoPE scaling type."""
    Linear = ...
    Su = ...
    Llama3 = ...


class MultiHeadAttentionSpec(model_spec.LayerSpec):
    def __init__(self, self_attention=..., relative_position=..., relative_asymmetric_position=..., relative_attention_bias=..., rms_norm=..., rotary_dim=..., rotary_interleave=..., rotary_scaling_type=..., rotary_scaling_factor=..., rotary_base=..., original_max_position_embeddings=..., max_position_embeddings=..., num_heads_kv=..., head_dim=..., sliding_window=..., qk_norm=..., qk_norm_rms=..., has_norm=...) -> None:
        ...
    


