"""
This type stub file was generated by pyright.
"""

import enum
from ctranslate2.specs import model_spec

class Activation(enum.IntEnum):
    """Activation type."""
    RELU = ...
    GELUTanh = ...
    SWISH = ...
    GELU = ...
    GELUSigmoid = ...
    Tanh = ...
    Sigmoid = ...


class EmbeddingsMerge(enum.IntEnum):
    """Merge strategy for factors embeddings."""
    CONCAT = ...
    ADD = ...


class Quantization(enum.IntEnum):
    """Activation type."""
    CT2 = ...
    AWQ_GEMM = ...
    AWQ_GEMV = ...


class LayerNormSpec(model_spec.LayerSpec):
    def __init__(self, rms_norm=...) -> None:
        ...
    


class LinearSpec(model_spec.LayerSpec):
    def __init__(self) -> None:
        ...
    
    def has_bias(self): # -> bool:
        ...
    


class Conv1DSpec(model_spec.LayerSpec):
    def __init__(self) -> None:
        ...
    


class EmbeddingsSpec(model_spec.LayerSpec):
    def __init__(self) -> None:
        ...
    


