"""
This type stub file was generated by pyright.
"""

import abc
import numpy as np
from typing import Dict, List, Optional

"""Specifications declare the expected variables layout of CTranslate2 models
that do not load a computation graph. The model converter should make sure that
each required variable of the specification is set.
"""
torch_is_available = ...
OPTIONAL = ...
CURRENT_BINARY_VERSION = ...
ACCEPTED_MODEL_TYPES = ...
SKIP_CREATING_ALIAS = ...
def visit_spec(spec, fn, scope=...): # -> None:
    """Recursively visits a layer spec."""
    ...

def index_spec(spec, index): # -> Any:
    ...

class FrozenMeta(type):
    def __call__(self, *args, **kwargs): # -> Any:
        ...
    


class FrozenAttr:
    def __setattr__(self, key, value): # -> None:
        ...
    


class LayerSpec(FrozenAttr, metaclass=FrozenMeta):
    """A layer specification declares the weights that should be set by the converters."""
    def validate(self) -> None:
        """Verify that the required weights are set.

        Raises:
          ValueError: If a required weight is not set in the specification.
        """
        ...
    
    def variables(self, prefix: str = ..., ordered: bool = ...) -> Dict[str, np.ndarray]:
        """Recursively returns the weights from this layer and its children.

        Arguments:
          prefix: Prefix to prepend to all variable names.
          ordered: If set, an ordered list is returned instead.

        Returns:
          Dictionary mapping variables name to value.
        """
        ...
    
    def optimize(self, quantization: Optional[str] = ...) -> None:
        """Recursively applies some optimizations to this layer:

        * Alias variables with the same shape and value.
        * Quantize weights.

        Arguments:
          quantization: Weight quantization scheme (possible values are: int8, int8_float32,
            int8_float16, int8_bfloat16, int16, float16, bfloat16, float32).
        """
        ...
    


class ModelConfig(FrozenAttr, metaclass=FrozenMeta):
    """Base class for model configurations."""
    def __init__(self, **kwargs) -> None:
        """Initializes the configuration with a set of parameters."""
        ...
    
    def to_dict(self): # -> dict[str, Any]:
        """Returns the configuration as a dictionary."""
        ...
    
    def add_attribute(self, key, value): # -> None:
        ...
    
    def save_as_json(self, path): # -> None:
        """Saves the configuration as a JSON file."""
        ...
    


class ModelSpec(LayerSpec):
    """The top level layer specification."""
    def __init__(self) -> None:
        """Initializes the model specification."""
        ...
    
    @property
    def name(self):
        """The name of the model specification."""
        ...
    
    @property
    def revision(self): # -> Literal[1]:
        """The model specification revision.

        This value is incremented each time the weights layout of the model is
        changed (e.g. a weight is renamed).
        """
        ...
    
    @property
    def config(self): # -> None:
        """The model configuration."""
        ...
    
    def get_default_config(self): # -> None:
        """Returns the default configuration used by this model."""
        ...
    
    def register_file(self, path: str, filename: Optional[str] = ...) -> None:
        """Registers a file to be saved in the model directory."""
        ...
    
    def save(self, output_dir: str) -> None:
        """Saves this model on disk.

        Arguments:
          output_dir: Output directory where the model is saved.
        """
        ...
    


class SequenceToSequenceModelConfig(ModelConfig):
    """Configuration for sequence-to-sequence models."""
    def __init__(self, unk_token: str = ..., bos_token: str = ..., eos_token: str = ..., decoder_start_token: Optional[str] = ..., add_source_bos: bool = ..., add_source_eos: bool = ..., **kwargs) -> None:
        """Initializes the configuration for sequence-to-sequence models.

        Args:
          unk_token: The unknown token.
          bos_token: The start of sentence token.
          eos_token: The end of sentence token.
          decoder_start_token: The decoder start token. If ``None``, the token should
            be passed by the user in the target prefix.
          add_source_bos: If ``True``, ``bos_token`` will be automatically added to
            the source input.
          add_source_eos: If ``True``, ``eos_token`` will be automatically added to
            the source input.
          **kwargs: Additional configuration.
        """
        ...
    


class SequenceToSequenceModelSpec(ModelSpec):
    """Base specification for sequence to sequence models."""
    def __init__(self) -> None:
        """Initializes a sequence to sequence model specification."""
        ...
    
    def get_default_config(self): # -> SequenceToSequenceModelConfig:
        ...
    
    @abc.abstractmethod
    def get_source_vocabulary_size(self):
        """Returns the source vocabulary size expected by the model."""
        ...
    
    @abc.abstractmethod
    def get_target_vocabulary_size(self):
        """Returns the target vocabulary size expected by the model."""
        ...
    
    def register_source_vocabulary(self, tokens: List[str]) -> None:
        """Registers a source vocabulary of tokens.

        Arguments:
          tokens: List of source tokens.
        """
        ...
    
    def register_target_vocabulary(self, tokens: List[str]) -> None:
        """Registers a target vocabulary of tokens.

        Arguments:
          tokens: List of target tokens.
        """
        ...
    
    def register_vocabulary_mapping(self, path: str) -> None:
        """Registers a vocabulary mapping file.

        Arguments:
          path: Path to the vocabulary mapping file.
        """
        ...
    
    def validate(self) -> None:
        ...
    
    def save(self, output_dir: str) -> None:
        ...
    


class LanguageModelConfig(ModelConfig):
    """Configuration for language models."""
    def __init__(self, unk_token: str = ..., bos_token: str = ..., eos_token: str = ..., **kwargs) -> None:
        """Initializes the configuration for language models.

        Args:
          unk_token: The unknown token.
          bos_token: The start of sentence token.
          eos_token: The end of sentence token.
          **kwargs: Additional configuration.
        """
        ...
    


class LanguageModelSpec(ModelSpec):
    """Base specification for language models."""
    def __init__(self) -> None:
        """Initializes a language model specification."""
        ...
    
    def get_default_config(self): # -> LanguageModelConfig:
        ...
    
    @abc.abstractmethod
    def get_vocabulary_size(self):
        """Returns the vocabulary size expected by the model."""
        ...
    
    def register_vocabulary(self, tokens: List[str]) -> None:
        """Registers the vocabulary of tokens.

        Arguments:
          tokens: List of tokens.
        """
        ...
    
    def validate(self) -> None:
        ...
    
    def save(self, output_dir: str) -> None:
        ...
    


class Variable(abc.ABC):
    """Abstract base class for model variables."""
    @property
    @abc.abstractmethod
    def shape(self) -> List[int]:
        ...
    
    def is_scalar(self) -> bool:
        ...
    
    @property
    @abc.abstractmethod
    def dtype(self) -> str:
        ...
    
    def to(self, dtype: str) -> Variable:
        ...
    
    @abc.abstractmethod
    def numpy(self) -> np.ndarray:
        ...
    
    def equal(self, other) -> bool:
        ...
    
    @abc.abstractmethod
    def num_bytes(self) -> int:
        ...
    
    @abc.abstractmethod
    def to_bytes(self) -> bytes:
        ...
    


class NumpyVariable(Variable):
    """Model variable as a Numpy array."""
    def __init__(self, array) -> None:
        ...
    
    @property
    def shape(self) -> List[int]:
        ...
    
    @property
    def dtype(self) -> str:
        ...
    
    def numpy(self) -> np.ndarray:
        ...
    
    def num_bytes(self) -> int:
        ...
    
    def to_bytes(self) -> bytes:
        ...
    


class PyTorchVariable(Variable):
    """Model variable as a PyTorch tensor."""
    def __init__(self, tensor) -> None:
        ...
    
    @classmethod
    def from_numpy(cls, array): # -> Self:
        ...
    
    @property
    def shape(self) -> List[int]:
        ...
    
    @property
    def dtype(self) -> str:
        ...
    
    def numpy(self) -> np.ndarray:
        ...
    
    def num_bytes(self) -> int:
        ...
    
    def to_bytes(self) -> bytes:
        ...
    


