"""
This type stub file was generated by pyright.
"""

from typing import Optional, Tuple, Union
from ctranslate2.specs import attention_spec, common_spec, model_spec

"""Declares specification of the Transformer model."""
class TransformerEncoderSpec(model_spec.LayerSpec):
    def __init__(self, num_layers: int, num_heads: int, pre_norm: bool = ..., no_final_norm: bool = ..., activation: common_spec.Activation = ..., num_source_embeddings: int = ..., embeddings_merge: common_spec.EmbeddingsMerge = ..., layernorm_embedding: bool = ..., relative_position: bool = ..., relative_attention_bias: bool = ..., ffn_glu: bool = ..., rms_norm: bool = ..., multi_query_attention: bool = ..., num_heads_kv: Optional[int] = ..., head_dim: Optional[int] = ..., rotary_dim: Optional[int] = ..., rotary_interleave: bool = ..., rotary_scaling_type: Optional[attention_spec.RotaryScalingType] = ..., rotary_scaling_factor: float = ..., rotary_base: float = ..., sliding_window: Optional[int] = ..., qk_norm: Optional[bool] = ..., pre_post_layer_norm: bool = ...) -> None:
        """Initializes a Transformer encoder specification.

        Args:
          num_layers: Number of layers.
          num_heads: Number of attention heads.
          pre_norm: Enable the pre-norm Transformer architecture.
          no_final_norm: Disable the final layer norm in the pre-norm architecture.
          activation: Activation to apply in the feed-forward network.
          num_source_embeddings: Number of source embeddings.
          embeddings_merge: When :obj:`num_source_embeddings` > 1, specify how the
            embeddings are merged.
          layernorm_embedding: Apply layer normalization after the embedding layer.
          relative_position: Use relative position representations in the self-attention
            layers as described in https://arxiv.org/abs/1803.02155.
          relative_attention_bias: Use relative attention bias in the self-attention
            layers as described in the T5 paper https://arxiv.org/abs/1910.10683.
          ffn_glu: Use gated linear units in the FFN layers as described in
            https://arxiv.org/abs/2002.05202.
          rms_norm: Use the root mean square layer normalization.
          multi_query_attention: Use multi-query attention (alias for num_heads_kv=1).
          num_heads_kv: Number of attention heads for the key and value.
          head_dim: Number of dimensions per attention head.
          rotary_dim: Apply rotary embeddings to these first N dimensions. If 0, rotary
            embeddings are applied to all dimensions.
          rotary_interleave: Interleave the head dimensions when rotary embeddings are applied.
            Otherwise the head dimensions are sliced in half.
          rotary_scaling_type: Type of RoPE scaling.
          rotary_scaling_factor: Factor used in the RoPE scaling.
          rotary_base: The base period of the rotary embeddings.
          sliding_window: Max sequence length to retain in KV Cache.
          qk_norm: Apply layer normalization to the query and key projections.
          pre_post_layer_norm: Add post layer norm for each pre norm layer.
        """
        ...
    


class TransformerDecoderSpec(model_spec.LayerSpec):
    def __init__(self, num_layers: int, num_heads: int, pre_norm: bool = ..., activation: common_spec.Activation = ..., layernorm_embedding: bool = ..., with_encoder_attention: bool = ..., no_final_norm: bool = ..., project_in_out: bool = ..., relative_position: bool = ..., relative_attention_bias: bool = ..., alignment_layer: int = ..., alignment_heads: int = ..., ffn_glu: bool = ..., rms_norm: bool = ..., alibi: bool = ..., alibi_use_positive_positions: bool = ..., scale_alibi: bool = ..., rotary_dim: Optional[int] = ..., rotary_interleave: bool = ..., rotary_scaling_type: Optional[attention_spec.RotaryScalingType] = ..., rotary_scaling_factor: float = ..., rotary_base: float = ..., original_max_position_embeddings: int = ..., max_position_embeddings: int = ..., parallel_residual: bool = ..., shared_layer_norm: bool = ..., pre_post_layer_norm: bool = ..., multi_query_attention: bool = ..., num_heads_kv: Optional[int] = ..., head_dim: Optional[int] = ..., sliding_window: Optional[int] = ..., quant_type: Optional[common_spec.Quantization] = ..., quant_group_size: Optional[int] = ..., quant_bits: Optional[int] = ..., qk_norm: bool = ..., external_pre_post_encoder_layers: Optional[bool] = ...) -> None:
        """Initializes a Transformer decoder specification.

        Args:
          num_layers: Number of layers.
          num_heads: Number of attention heads.
          pre_norm: Enable the pre-norm Transformer architecture.
          activation: Activation to apply in the feed-forward network.
          layernorm_embedding: Apply layer normalization after the embedding layer.
          with_encoder_attention: Enable the encoder attention sublayers.
          no_final_norm: Disable the final layer norm in the pre-norm architecture.
          project_in_out: Add linear transformations after the embedding layer and before
            the final layer.
          relative_position: Use relative position representations in the self-attention
            layers as described in https://arxiv.org/abs/1803.02155.
          relative_attention_bias: Use relative attention bias in the self-attention
            layers as described in the T5 paper https://arxiv.org/abs/1910.10683.
          alignment_layer: Layer index selected for alignment.
          alignment_heads: Number of attention heads selected for alignment.
          ffn_glu: Use gated linear units in the FFN layers as described in
            https://arxiv.org/abs/2002.05202.
          rms_norm: Use the root mean square layer normalization.
          alibi: Use attention with linear biases.
          alibi_use_positive_positions: Use positive positions in the ALiBi definition.
          scale_alibi: Apply the dot product scale factor to ALiBi.
          rotary_dim: Apply rotary embeddings to these first N dimensions. If 0, rotary
            embeddings are applied to all dimensions.
          rotary_interleave: Interleave the head dimensions when rotary embeddings are applied.
            Otherwise the head dimensions are sliced in half.
          rotary_scaling_type: Type of RoPE scaling.
          rotary_scaling_factor: Factor used in the RoPE scaling.
          rotary_base: The base period of the rotary embeddings.
          original_max_position_embeddings: The original max position embeddings
            for Su rope embeddings
          max_position_embeddings: The max position embeddings for Su rope embeddings
          parallel_residual: Use parallel residual connections in each layer block, as used
            by the GPT-J and GPT-NeoX models.
          shared_layer_norm: When using parallel residual, share the input and post
            attention layer norms.
          pre_post_layer_norm: Add post layer norm for each pre norm layer
          multi_query_attention: Use multi-query attention (alias for num_heads_kv=1).
          num_heads_kv: Number of attention heads for the key and value.
          sliding_window: Max sequence length to retain in KV Cache.
          quant_type: quantization type used (like awq... for lower bit quantization)
          quant_group_size: group size of the lower bit quantization
          quant_bits: number of bit of the quantization (ex: 4bit)
          external_pre_post_encoder_layers: if the encoder attention pre and processing
            is done outside the attention.
        """
        ...
    
    @property
    def config(self): # -> dict[Any, Any]:
        ...
    


class TransformerEncoderLayerSpec(model_spec.LayerSpec):
    def __init__(self, relative_position=..., relative_attention_bias=..., ffn_glu=..., rms_norm=..., num_heads_kv=..., head_dim=..., sliding_window=..., rotary_dim: Optional[int] = ..., rotary_interleave: bool = ..., rotary_scaling_type: Optional[attention_spec.RotaryScalingType] = ..., rotary_scaling_factor: float = ..., rotary_base: float = ..., qk_norm=..., pre_post_layer_norm: bool = ...) -> None:
        ...
    


class TransformerDecoderLayerSpec(model_spec.LayerSpec):
    def __init__(self, with_encoder_attention=..., relative_position=..., relative_attention_bias=..., ffn_glu=..., rms_norm=..., rotary_dim=..., rotary_interleave=..., rotary_scaling_type=..., rotary_scaling_factor=..., rotary_base=..., original_max_position_embeddings=..., max_position_embeddings=..., parallel_residual=..., shared_layer_norm=..., pre_post_layer_norm=..., num_heads_kv=..., head_dim=..., sliding_window=..., qk_norm=..., external_pre_post_encoder_layers=...) -> None:
        ...
    


class FeedForwardSpec(model_spec.LayerSpec):
    def __init__(self, glu=..., rms_norm=...) -> None:
        ...
    


class PositionEncoderSpec(model_spec.LayerSpec):
    def __init__(self) -> None:
        ...
    


class TransformerConfig(model_spec.SequenceToSequenceModelConfig):
    """Configuration for Transformer models."""
    def __init__(self, layer_norm_epsilon: Optional[float] = ..., **kwargs) -> None:
        """Initializes the configuration for Transformer models.

        Args:
          layer_norm_epsilon: The layer norm epsilon value.
          **kwargs: Additional configuration.
        """
        ...
    


class TransformerSpec(model_spec.SequenceToSequenceModelSpec):
    """Describes a Transformer model.

    The specification is invariant to hidden dimensions but requires to
    explicitly set the number of layers and attention heads.
    """
    def __init__(self, encoder: TransformerEncoderSpec, decoder: TransformerDecoderSpec) -> None:
        """Initializes a Transformer model specification.

        Args:
          encoder: The encoder specification.
          decoder: The decoder specification.
        """
        ...
    
    @classmethod
    def from_config(cls, num_layers: Union[int, Tuple[int, int]], num_heads: int, with_relative_position: bool = ..., pre_norm: bool = ..., no_final_norm: bool = ..., activation: common_spec.Activation = ..., alignment_layer: int = ..., alignment_heads: int = ..., num_source_embeddings: int = ..., embeddings_merge: common_spec.EmbeddingsMerge = ..., layernorm_embedding: bool = ..., relative_attention_bias: bool = ..., ffn_glu: bool = ..., rms_norm: bool = ..., multi_query_attention: bool = ...): # -> Self:
        """Creates a Transformer model specification.

        Args:
          num_layers: Number of encoder and decoder layers, or a 2-tuple if the
            number is different.
          num_heads: Number of attention heads.
          with_relative_position: Use relative position representations in the self-attention
            layers as described in https://arxiv.org/abs/1803.02155.
          pre_norm: Enable the pre-norm Transformer architecture.
          no_final_norm: Disable the final layer norm in the pre-norm architecture.
          activation: Activation to apply in the feed-forward network.
          alignment_layer: Layer index selected for alignment.
          alignment_heads: Number of attention heads selected for alignment.
          num_source_embeddings: Number of source embeddings.
          embeddings_merge: When :obj:`num_source_embeddings` > 1, specify how the
            embeddings are merged.
          layernorm_embedding: Apply layer normalization after the embedding layer.
          relative_attention_bias: Use relative attention bias in the self-attention
            layers as described in the T5 paper https://arxiv.org/abs/1910.10683.
          ffn_glu: Use gated linear units in the FFN layer as described in
            https://arxiv.org/abs/2002.05202.
          rms_norm: Use the root mean square layer normalization.
          multi_query_attention: Use multi-query attention.
        """
        ...
    
    @property
    def name(self): # -> Literal['TransformerSpec']:
        ...
    
    @property
    def revision(self): # -> Literal[7]:
        ...
    
    def get_default_config(self): # -> TransformerConfig:
        ...
    
    def get_source_vocabulary_size(self): # -> list[Any]:
        ...
    
    def get_target_vocabulary_size(self):
        ...
    


class TransformerDecoderModelConfig(model_spec.LanguageModelConfig):
    """Configuration for Transformer decoder models."""
    def __init__(self, layer_norm_epsilon: Optional[float] = ..., **kwargs) -> None:
        """Initializes the configuration for Transformer decoder models.

        Args:
          layer_norm_epsilon: The layer norm epsilon value.
          **kwargs: Additional configuration.
        """
        ...
    


class TransformerDecoderModelSpec(model_spec.LanguageModelSpec):
    """Describes a Transformer decoder model (e.g. GPT-2)."""
    def __init__(self, decoder: TransformerDecoderSpec) -> None:
        """Initializes a Transformer decoder model specification.

        Args:
          decoder: The decoder specification.
        """
        ...
    
    @classmethod
    def from_config(cls, num_layers: int, num_heads: int, pre_norm: bool = ..., activation: common_spec.Activation = ..., layernorm_embedding: bool = ..., no_final_norm: bool = ..., project_in_out: bool = ..., with_relative_position: bool = ..., ffn_glu: bool = ..., rms_norm: bool = ..., alibi: bool = ..., alibi_use_positive_positions: bool = ..., scale_alibi: bool = ..., rotary_dim: Optional[int] = ..., rotary_interleave: bool = ..., rotary_scaling_type: Optional[attention_spec.RotaryScalingType] = ..., rotary_scaling_factor: float = ..., rotary_base: float = ..., original_max_position_embeddings: int = ..., max_position_embeddings: int = ..., parallel_residual: bool = ..., shared_layer_norm: bool = ..., pre_post_layer_norm: bool = ..., multi_query_attention: bool = ..., num_heads_kv: Optional[int] = ..., head_dim: Optional[int] = ..., sliding_window: Optional[int] = ..., quant_type: Optional[common_spec.Quantization] = ..., quant_group_size: Optional[int] = ..., quant_bits: Optional[int] = ..., qk_norm: bool = ...): # -> Self:
        """Creates a Transformer decoder model specification.

        Args:
          num_layers: Number of decoder layers.
          num_heads: Number of attention heads.
          pre_norm: Enable the pre-norm Transformer architecture.
          activation: Activation to apply in the feed-forward network.
          layernorm_embedding: Apply layer normalization after the embedding layer.
          no_final_norm: Do not apply layer normalization after the last decoder block.
          project_in_out: Add a linear layer after the embedding layer and another one
            before the final output projection.
          with_relative_position: Enable relative position representations modules.
          ffn_glu: Use gated linear units in the FFN layers as described in
            https://arxiv.org/abs/2002.05202.
          rms_norm: Use the root mean square layer normalization.
          alibi: Use attention with linear biases.
          alibi_use_positive_positions: Use positive positions in the ALiBi definition.
          scale_alibi: Apply the dot product scale factor to ALiBi.
          rotary_dim: Apply rotary embeddings to these first N dimensions. If 0, rotary
            embeddings are applied to all dimensions.
          rotary_interleave: Interleave the head dimensions when rotary embeddings are applied.
            Otherwise the head dimensions are sliced in half.
          rotary_scaling_type: Type of RoPE scaling.
          rotary_scaling_factor: Factor used in the RoPE scaling.
          rotary_base: The base period of the rotary embeddings.
          original_max_position_embeddings: The original max position embeddings
            for Su rope embeddings
          max_position_embeddings: The max position embeddings for Su rope embeddings
          parallel_residual: Use parallel residual connections in each layer block, as used
            by the GPT-J and GPT-NeoX models.
          shared_layer_norm: When using parallel residual, share the input and post
            attention layer norms.
          pre_post_layer_norm: add post layer norm for each pre norm layer
          multi_query_attention: Use multi-query attention (alias for num_heads_kv=1).
          num_heads_kv: Number of attention heads for the key and value.
          head_dim: Number of head
          sliding_window: max sequence length to retain KV cache
          quant_type: quantization type used (like awq... for lower bit quantization)
          quant_group_size: group size of the lower bit quantization
          quant_bits: number of bit of the quantization (ex: 4bit)
        """
        ...
    
    @property
    def name(self): # -> Literal['TransformerDecoderSpec']:
        ...
    
    @property
    def revision(self): # -> Literal[8]:
        ...
    
    def get_default_config(self): # -> TransformerDecoderModelConfig:
        ...
    
    def get_vocabulary_size(self):
        ...
    


class TransformerEncoderModelConfig(model_spec.LanguageModelConfig):
    """Configuration for Transformer encoder models."""
    def __init__(self, layer_norm_epsilon: Optional[float] = ..., **kwargs) -> None:
        """Initializes the configuration for Transformer encoder models.

        Args:
          layer_norm_epsilon: The layer norm epsilon value.
          **kwargs: Additional configuration.
        """
        ...
    


class TransformerEncoderModelSpec(model_spec.LanguageModelSpec):
    """Describes a Transformer encoder model (e.g. BERT)."""
    def __init__(self, encoder: TransformerEncoderSpec, pooling_layer: bool = ..., pooling_activation: common_spec.Activation = ...) -> None:
        """Initializes a Transformer encoder model specification.

        Args:
          encoder: The encoder specification.
          pooling_layer: Add the pooling layer.
          pooling_activation: The activation to apply after the pooling layer.
        """
        ...
    
    @property
    def name(self): # -> Literal['TransformerEncoderSpec']:
        ...
    
    @property
    def revision(self): # -> Literal[1]:
        ...
    
    def get_default_config(self): # -> TransformerEncoderModelConfig:
        ...
    
    def get_vocabulary_size(self):
        ...
    


