"""
This type stub file was generated by pyright.
"""

from ctranslate2.specs import model_spec

class Wav2Vec2BertConfig(model_spec.ModelConfig):
    """Configuration for the Wav2Vec2Bert model."""
    def __init__(self) -> None:
        ...
    


class Wav2Vec2BertSpec(model_spec.LanguageModelSpec):
    def __init__(self, num_hidden_layers, num_adapter_layers, vocab_size, return_hidden) -> None:
        ...
    
    @property
    def name(self): # -> Literal['Wav2Vec2BertSpec']:
        ...
    
    @property
    def revision(self): # -> Literal[1]:
        ...
    
    def get_default_config(self): # -> Wav2Vec2BertConfig:
        ...
    
    def get_vocabulary_size(self): # -> int:
        ...
    


class Wav2Vec2BertFeedForwardSpec(model_spec.LayerSpec):
    def __init__(self, glu=..., rms_norm=...) -> None:
        ...
    


class EncoderSpec(model_spec.LayerSpec):
    def __init__(self) -> None:
        ...
    


class AdapterSpec(model_spec.LayerSpec):
    def __init__(self) -> None:
        ...
    


class Wav2Vec2BertEncoderSpec(model_spec.LayerSpec):
    def __init__(self, num_hidden_layers, num_adapter_layers, return_hidden) -> None:
        ...
    


