"""
This type stub file was generated by pyright.
"""

from ctranslate2.specs import model_spec

class Wav2Vec2Config(model_spec.ModelConfig):
    """Configuration for the Wav2Vec2 model."""
    def __init__(self) -> None:
        ...
    


class Wav2Vec2Spec(model_spec.LanguageModelSpec):
    def __init__(self, feat_layers, num_layers, num_heads, vocab_size, return_hidden) -> None:
        ...
    
    @property
    def name(self): # -> Literal['Wav2Vec2Spec']:
        ...
    
    @property
    def revision(self): # -> Literal[3]:
        ...
    
    def get_default_config(self): # -> Wav2Vec2Config:
        ...
    
    def get_vocabulary_size(self): # -> int:
        ...
    


class Wav2Vec2LayerNormConvLayer(model_spec.LayerSpec):
    def __init__(self) -> None:
        ...
    


class Wav2Vec2PosEmbedConvLayer(model_spec.LayerSpec):
    def __init__(self) -> None:
        ...
    


class Wav2Vec2EncoderSpec(model_spec.LayerSpec):
    def __init__(self, feat_layers, num_layers, num_heads, return_hidden) -> None:
        ...
    


