"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Tuple
from ctranslate2.specs import model_spec

class WhisperConfig(model_spec.ModelConfig):
    """Configuration for the Whisper model."""
    def __init__(self, suppress_ids: Optional[List[int]] = ..., suppress_ids_begin: Optional[List[int]] = ..., lang_ids: Optional[List[int]] = ..., alignment_heads: Optional[List[Tuple[int, int]]] = ...) -> None:
        ...
    


class WhisperSpec(model_spec.LanguageModelSpec):
    """Describes a Whisper model."""
    def __init__(self, num_encoder_layers, num_encoder_heads, num_decoder_layers, num_decoder_heads) -> None:
        """Initializes the model specification.

        Args:
          num_encoder_layers: The number of encoder layers.
          num_encoder_heads: The number of encoder attention heads.
          num_decoder_layers: The number of decoder layers.
          num_decoder_heads: The number of decoder attention heads.
        """
        ...
    
    @property
    def name(self): # -> Literal['WhisperSpec']:
        ...
    
    @property
    def revision(self): # -> Literal[3]:
        ...
    
    def get_default_config(self): # -> WhisperConfig:
        ...
    
    def get_vocabulary_size(self):
        ...
    


class WhisperEncoderSpec(model_spec.LayerSpec):
    def __init__(self, num_layers, num_heads) -> None:
        ...
    


