import openai
import requests


import os
from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv("APERTIS_TOKEN")

# headers = {
#     "Content-Type": "application/json",
#     "Authorization": f"Bearer {api_key}",
# }

# response = requests.get("https://api.apertis.ai/v1/models", headers=headers)

# print(response.json())

client = openai.OpenAI(base_url="https://api.apertis.ai/v1", api_key=api_key)

resp = client.chat.completions.create(
    model="glm-4.5-air:free",
    messages=[
        {
            "role": "user",
            "content": "Напиши Python функцию для суммирования двух чисел",
        }
    ],
)

print(resp)
print("#####")
print(resp.choices[0].message.content)

# {
#     "object": "list",
#     "data": [
#         {
#             "id": "doubao-seedream-4-0-250828",
#             "object": "model",
#             "created": 1756310400,
#             "owned_by": "bytedance",
#         },
#         {
#             "id": "command-r-plus-08-2024",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ernie-4.5-turbo-vl-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "fal-ai/nano-banana",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4-turbo",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-4-scout:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "veo3.1",
#             "object": "model",
#             "created": 1768406400,
#             "owned_by": "google",
#         },
#         {
#             "id": "codestral-embed-2505",
#             "object": "model",
#             "created": 1761753600,
#             "owned_by": "mistralai",
#         },
#         {
#             "id": "grok-code-fast-1",
#             "object": "model",
#             "created": 1756137600,
#             "owned_by": "xai",
#         },
#         {
#             "id": "gemini-2.5-flash-lite-preview-09-2025",
#             "object": "model",
#             "created": 1758729600,
#             "owned_by": "google",
#         },
#         {
#             "id": "llama-guard-4-12b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen2.5-vl-32b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5.2-chat",
#             "object": "model",
#             "created": 1765296000,
#             "owned_by": "openai",
#         },
#         {"id": "grok-4.1", "object": "model", "created": 1763308800, "owned_by": "xai"},
#         {
#             "id": "gemini-3-pro-preview-11-2025-thinking",
#             "object": "model",
#             "created": 1763395200,
#             "owned_by": "google",
#         },
#         {
#             "id": "ernie-4.5-21b-a3b-thinking",
#             "object": "model",
#             "created": 1759939200,
#             "owned_by": "baidu",
#         },
#         {
#             "id": "ernie-4.5-0.3b-a3b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "seed-2.0-mini",
#             "object": "model",
#             "created": 1772035200,
#             "owned_by": "bytedance",
#         },
#         {
#             "id": "gpt-oss-20b",
#             "object": "model",
#             "created": 1754323200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gpt-5.1-codex-max",
#             "object": "model",
#             "created": 1764777600,
#             "owned_by": "openai",
#         },
#         {
#             "id": "kat-coder-pro",
#             "object": "model",
#             "created": 1762704000,
#             "owned_by": "kwaipilot",
#         },
#         {
#             "id": "gpt-4o-mini-2024-07-18",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "mistral-medium-3.1",
#             "object": "model",
#             "created": 1755014400,
#             "owned_by": "mistralai",
#         },
#         {
#             "id": "ERNIE-3.5-8K",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "tng-r1t-chimera",
#             "object": "model",
#             "created": 1764086400,
#             "owned_by": "tngtech",
#         },
#         {
#             "id": "claude-3-sonnet-20240229",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "command-a",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4-0314",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4o-search-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-embedding-001",
#             "object": "model",
#             "created": 1770652800,
#             "owned_by": "google",
#         },
#         {
#             "id": "claude-opus-4-6",
#             "object": "model",
#             "created": 1770307200,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "nova-2-lite-v1:free",
#             "object": "model",
#             "created": 1764604800,
#             "owned_by": "amazon",
#         },
#         {
#             "id": "gpt-4o",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwq-32b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "mistral-7b-instruct-v0.3",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "o3-pro",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-3.1-flash-lite-preview",
#             "object": "model",
#             "created": 1772467200,
#             "owned_by": "google",
#         },
#         {
#             "id": "kimi-k2.5",
#             "object": "model",
#             "created": 1769443200,
#             "owned_by": "moonshotai",
#         },
#         {
#             "id": "command-r-03-2024",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.1-nemotron-ultra-253b-v1:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-guard-3-8b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "o1-pro",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "claude-opus-4-1-20250805",
#             "object": "model",
#             "created": 1754323200,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "codestral-2501",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.2-90b-vision-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "kimi-k2-0905",
#             "object": "model",
#             "created": 1756915200,
#             "owned_by": "moonshotai",
#         },
#         {
#             "id": "dall-e-3",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "deepseek-r1-distill-qwen-14b:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4o-search-preview-2025-03-11",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.1-405b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "mistral-large-2411",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "mixtral-8x7b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemma-3n-e4b-it:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "jina-embeddings-v2-base-en",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "nova-premier-v1",
#             "object": "model",
#             "created": 1761840000,
#             "owned_by": "amazon",
#         },
#         {
#             "id": "mistral-small-3.2-24b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ernie-4.5-vl-28b-a3b",
#             "object": "model",
#             "created": 1754928000,
#             "owned_by": "baidu",
#         },
#         {
#             "id": "glm-4.5-flash",
#             "object": "model",
#             "created": 1753372800,
#             "owned_by": "z.ai",
#         },
#         {
#             "id": "ERNIE-Speed-8K",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5.3-chat",
#             "object": "model",
#             "created": 1772467200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "deepseek-r1-0528-qwen3-8b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "grok-3",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "claude-3-opus-20240229",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "glm-4.6v",
#             "object": "model",
#             "created": 1765123200,
#             "owned_by": "z.ai",
#         },
#         {
#             "id": "nova-2-lite-v1",
#             "object": "model",
#             "created": 1764604800,
#             "owned_by": "amazon",
#         },
#         {
#             "id": "gpt-5.1-high",
#             "object": "model",
#             "created": 1762963200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gpt-3.5-turbo-0301",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-4-maverick:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "Qwen/Qwen3-Reranker-0.6B",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "tts-1",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5.3-codex-high",
#             "object": "model",
#             "created": 1770307200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "qwen3-max",
#             "object": "model",
#             "created": 1758556800,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "gemini-3-pro-preview",
#             "object": "model",
#             "created": 1763395200,
#             "owned_by": "google",
#         },
#         {
#             "id": "gpt-5.1",
#             "object": "model",
#             "created": 1762963200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gpt-3.5-turbo",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "olympiccoder-32b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4o-mini-audio-preview-2024-12-17",
#             "object": "model",
#             "created": 1734364800,
#             "owned_by": "openai",
#         },
#         {
#             "id": "deepseek-r1-distill-llama-70b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen-turbo",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4-32k-0613",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "doubao-seedream-3-0-t2i-250415",
#             "object": "model",
#             "created": 1744646400,
#             "owned_by": "bytedance",
#         },
#         {
#             "id": "gpt-5.1-codex-mini",
#             "object": "model",
#             "created": 1762963200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gemini-2.5-flash-image",
#             "object": "model",
#             "created": 1759766400,
#             "owned_by": "google",
#         },
#         {
#             "id": "qwen3-vl-235b-a22b-instruct",
#             "object": "model",
#             "created": 1758556800,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "deepseek-v3:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "devstral-small-2507",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-4b:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5.3-codex-low",
#             "object": "model",
#             "created": 1770307200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "codex-mini",
#             "object": "model",
#             "created": 1747324800,
#             "owned_by": "openai",
#         },
#         {
#             "id": "mistral-large-2512",
#             "object": "model",
#             "created": 1764518400,
#             "owned_by": "mistralai",
#         },
#         {
#             "id": "qwen3-coder-plus",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "grok-4.1-image",
#             "object": "model",
#             "created": 1772467200,
#             "owned_by": "xai",
#         },
#         {
#             "id": "gemini-3.1-pro-preview",
#             "object": "model",
#             "created": 1771430400,
#             "owned_by": "google",
#         },
#         {
#             "id": "gemini-3-pro-preview-thinking",
#             "object": "model",
#             "created": 1763395200,
#             "owned_by": "google",
#         },
#         {
#             "id": "deepseek-r1-0528:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "deepseek-r1:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "deepseek-v3-search",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3-8b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "perplexity-r1-1776",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "claude-opus-4-1-20250805-thinking",
#             "object": "model",
#             "created": 1754323200,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "gpt-4-0125-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen-plus",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen2.5-32b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen2.5-vl-72b-instruct:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-14b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ministral-8b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3.5-397b-a17b",
#             "object": "model",
#             "created": 1771255322,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "codestral-2508",
#             "object": "model",
#             "created": 1753977600,
#             "owned_by": "mistralai",
#         },
#         {
#             "id": "gemini-2.5-flash",
#             "object": "model",
#             "created": 1750089600,
#             "owned_by": "google",
#         },
#         {
#             "id": "magistral-medium-2506:thinking",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "mai-ds-r1:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "tongyi-deepresearch-30b-a3b",
#             "object": "model",
#             "created": 1758124800,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "grok-3-beta",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "kimi-k2",
#             "object": "model",
#             "created": 1756915200,
#             "owned_by": "moonshotai",
#         },
#         {
#             "id": "command-r",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ERNIE-Speed-128K",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.1-sonar-large-128k-chat",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {"id": "o3", "object": "model", "created": 1723766400, "owned_by": "apertis"},
#         {
#             "id": "pixtral-large-2411",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-2.5-flash-preview",
#             "object": "model",
#             "created": 1758729600,
#             "owned_by": "google",
#         },
#         {
#             "id": "gpt-5.2",
#             "object": "model",
#             "created": 1765296000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gemini-2.0-flash-001",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4.1",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4o-2024-05-13",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "horizon-beta",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "jina-embeddings-v2-base-zh",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "moonlight-16b-a3b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "moonshot-v1-128k",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "kimi-k2-0711-preview-search",
#             "object": "model",
#             "created": 1752163200,
#             "owned_by": "moonshotai",
#         },
#         {
#             "id": "devstral-small",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "Qwen/Qwen3-Reranker-8B",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-0.6b-04-28:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-vl-8b-instruct",
#             "object": "model",
#             "created": 1760371200,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "gemini-2.0-flash-thinking-exp-0121:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemma-3-27b-it:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4.1-mini",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "mistral-large-2407",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qvq-72b-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "doubao-seedream-5-0-260128",
#             "object": "model",
#             "created": 1769529600,
#             "owned_by": "bytedance",
#         },
#         {
#             "id": "olmo-3.1-32b-think:free",
#             "object": "model",
#             "created": 1765814400,
#             "owned_by": "allenai",
#         },
#         {
#             "id": "gpt-5.1-codex",
#             "object": "model",
#             "created": 1762963200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "deepseek-r1-0528",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemma-2-9b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "mistral-7b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-235b-a22b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5.4",
#             "object": "model",
#             "created": 1772640000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "ernie-4.5-turbo-128k",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5-mini-2025-08-07",
#             "object": "model",
#             "created": 1754496000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "devstral-small:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ernie-4.5-turbo-32k",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.1-nemotron-70b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen-max",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ernie-4.5-21b-a3b",
#             "object": "model",
#             "created": 1754928000,
#             "owned_by": "baidu",
#         },
#         {"id": "glm-4.5", "object": "model", "created": 1753372800, "owned_by": "z.ai"},
#         {
#             "id": "gemini-2.5-flash-preview-05-20:thinking",
#             "object": "model",
#             "created": 1747670400,
#             "owned_by": "google",
#         },
#         {
#             "id": "gpt-5.1-medium",
#             "object": "model",
#             "created": 1762963200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "kimi-k2-thinking",
#             "object": "model",
#             "created": 1762358400,
#             "owned_by": "moonshotai",
#         },
#         {
#             "id": "BAAI/bge-reranker-v2-m3",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "nemotron-nano-9b-v2",
#             "object": "model",
#             "created": 1757001600,
#             "owned_by": "nvidia",
#         },
#         {
#             "id": "text-embedding-ada-002",
#             "object": "model",
#             "created": 1671638400,
#             "owned_by": "openai",
#         },
#         {
#             "id": "grok-3-mini-beta",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.2-3b-instruct:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "deepseek-v3.2-thinking",
#             "object": "model",
#             "created": 1764554400,
#             "owned_by": "deepseek",
#         },
#         {
#             "id": "claude-sonnet-4-20250514",
#             "object": "model",
#             "created": 1747843200,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "qwen3-235b-a22b-07-25",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-30b-a3b",
#             "object": "model",
#             "created": 1756310400,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "gpt-5.1-thinking",
#             "object": "model",
#             "created": 1762963200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "grok-4",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5-pro",
#             "object": "model",
#             "created": 1759680000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "llama-3.3-8b-instruct:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-30b-a3b:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "claude-sonnet-4-6",
#             "object": "model",
#             "created": 1771257600,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "sora-2",
#             "object": "model",
#             "created": 1759161600,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gemini-2.0-pro-exp-02-05",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "sonar",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-2.5-pro-deepsearch",
#             "object": "model",
#             "created": 1750089600,
#             "owned_by": "google",
#         },
#         {
#             "id": "deepseek-chat-v3-0324",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-2.0-flash-lite-preview-02-05",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemma-3-4b-it",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.2-1b-instruct:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen-2.5-coder-32b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {"id": "veo3", "object": "model", "created": 1723766400, "owned_by": "apertis"},
#         {
#             "id": "sonar-pro-search",
#             "object": "model",
#             "created": 1761753600,
#             "owned_by": "perplexity",
#         },
#         {
#             "id": "qwen3-coder-flash",
#             "object": "model",
#             "created": 1758038400,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "claude-sonnet-4.5",
#             "object": "model",
#             "created": 1759075200,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "claude-opus-4-5-20251101-thinking",
#             "object": "model",
#             "created": 1763913600,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "ernie-4.5-8k-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-3.5-turbo-16k-0613",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "moonshot-v1-8k",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "phi-4",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "phi-4-reasoning-plus",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen-vl-plus",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "o3-deep-research",
#             "object": "model",
#             "created": 1760025600,
#             "owned_by": "openai",
#         },
#         {
#             "id": "llama-3.1-sonar-small-128k-online",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "deepseek-prover-v2",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "mistral-small-3.1-24b-instruct-2503",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ernie-x1-32k-preview",
#             "object": "model",
#             "created": 1748707200,
#             "owned_by": "baidu",
#         },
#         {
#             "id": "gemini-2.5-flash-preview:thinking",
#             "object": "model",
#             "created": 1758729600,
#             "owned_by": "google",
#         },
#         {
#             "id": "voxtral-small-24b-2507",
#             "object": "model",
#             "created": 1761753600,
#             "owned_by": "mistralai",
#         },
#         {
#             "id": "deepseek-r1-distill-qwen-32b:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "o1-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "o3-mini-high",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "grok-4.2-image",
#             "object": "model",
#             "created": 1772467200,
#             "owned_by": "xai",
#         },
#         {
#             "id": "claude-3.7-sonnet-thinking",
#             "object": "model",
#             "created": 1740326400,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "gemini-1.5-flash-002",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-1.5-flash-latest",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3.5-35b-a3b",
#             "object": "model",
#             "created": 1771948800,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "gpt-4o-audio-preview",
#             "object": "model",
#             "created": 1755187200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gpt-5-2025-08-07",
#             "object": "model",
#             "created": 1754496000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gpt-oss-safeguard-20b",
#             "object": "model",
#             "created": 1761667200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "grok-3-deepsearch",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen-plus-2025-07-28",
#             "object": "model",
#             "created": 1757260800,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "llama-3.2-3b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5.1-chat",
#             "object": "model",
#             "created": 1762963200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "o1-preview-2024-09-12",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen2.5-vl-32b-instruct:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "command-r-plus-04-2024",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "grok-3-search",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ernie-x1-turbo-32k",
#             "object": "model",
#             "created": 1748707200,
#             "owned_by": "baidu",
#         },
#         {
#             "id": "text-embedding-3-small",
#             "object": "model",
#             "created": 1706112000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "olmo-3-32b-think",
#             "object": "model",
#             "created": 1765814400,
#             "owned_by": "allenai",
#         },
#         {
#             "id": "kimi-dev-72b:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "claude-opus-4-6-thinking",
#             "object": "model",
#             "created": 1770307200,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "veo3.1-fast-4k",
#             "object": "model",
#             "created": 1768492800,
#             "owned_by": "google",
#         },
#         {
#             "id": "gpt-audio-2025-08-28",
#             "object": "model",
#             "created": 1756310400,
#             "owned_by": "openai",
#         },
#         {
#             "id": "llama-3-70b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "o4-mini-high",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen-2.5-7b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "sonar-reasoning",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "minimax-m2",
#             "object": "model",
#             "created": 1761148800,
#             "owned_by": "minimax",
#         },
#         {
#             "id": "qwen3-vl-8b-thinking",
#             "object": "model",
#             "created": 1760371200,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "gemini-2.5-flash-image-preview",
#             "object": "model",
#             "created": 1756137600,
#             "owned_by": "google",
#         },
#         {
#             "id": "gpt-3.5-turbo-0613",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4o-2024-11-20",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "tts-1-hd-1106",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "o4-mini",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-coder:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "veo3.1-4k",
#             "object": "model",
#             "created": 1768406400,
#             "owned_by": "google",
#         },
#         {
#             "id": "deepseek-r1-distill-qwen-32b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "jina-clip-v2",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ministral-3b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-3.5-turbo-0125",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-30b-a3b-think",
#             "object": "model",
#             "created": 1756310400,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "grok-4-image",
#             "object": "model",
#             "created": 1751990400,
#             "owned_by": "xai",
#         },
#         {
#             "id": "claude-3-5-haiku-20241022",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "deepseek-r1-distill-qwen-1.5b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-2.0-flash-thinking-exp-01-21",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "nemotron-nano-12b-v2-vl",
#             "object": "model",
#             "created": 1761580800,
#             "owned_by": "nvidia",
#         },
#         {
#             "id": "deepseek-r1-distill-qwen-7b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemma-2-27b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "mistral-small-24b-instruct-2501",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4o-audio-preview-2025-06-03",
#             "object": "model",
#             "created": 1748880000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "llama-3.2-1b-instruct",
#             "object": "model",
#             "created": 1727193600,
#             "owned_by": "meta",
#         },
#         {
#             "id": "sora-2-portrait",
#             "object": "model",
#             "created": 1759161600,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gemma-3-12b-it",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.1-sonar-huge-128k-online",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "glm-4.5-airx",
#             "object": "model",
#             "created": 1753372800,
#             "owned_by": "z.ai",
#         },
#         {
#             "id": "gemini-3-pro-preview-11-2025",
#             "object": "model",
#             "created": 1763395200,
#             "owned_by": "google",
#         },
#         {
#             "id": "gpt-4o-audio-preview-2024-10-01",
#             "object": "model",
#             "created": 1727712000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "jina-colbert-v2",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "jinaai",
#         },
#         {
#             "id": "gemini-exp-1206",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4-vision-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "phi-4-reasoning-plus:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3.5-27b",
#             "object": "model",
#             "created": 1771948800,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "ernie-x1-32k",
#             "object": "model",
#             "created": 1748707200,
#             "owned_by": "baidu",
#         },
#         {
#             "id": "gemma-2-9b-it:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4o-2024-08-06",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "kimi-vl-a3b-thinking:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {"id": "o1", "object": "model", "created": 1723766400, "owned_by": "apertis"},
#         {
#             "id": "gemma-3-12b-it:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen-2.5-72b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "grok-4.1-fast:free",
#             "object": "model",
#             "created": 1763481600,
#             "owned_by": "xai",
#         },
#         {
#             "id": "gemini-2.0-flash-exp",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "grok-4-fast:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "o3-mini",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5-search-api",
#             "object": "model",
#             "created": 1760371200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "doubao-seedream-4-5-251128",
#             "object": "model",
#             "created": 1764259200,
#             "owned_by": "bytedance",
#         },
#         {
#             "id": "qwen3.5-122b-a10b",
#             "object": "model",
#             "created": 1771948800,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "gpt-5-chat-latest",
#             "object": "model",
#             "created": 1754496000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "deepseek-chat-v3.1",
#             "object": "model",
#             "created": 1755705600,
#             "owned_by": "deepseek",
#         },
#         {
#             "id": "deepseek-v2.5",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4-turbo-2024-04-09",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen2.5-coder-7b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemma-3-27b-it",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.1-sonar-large-128k-online",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.3-nemotron-super-49b-v1:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-2.5-flash-preview-09-2025",
#             "object": "model",
#             "created": 1758729600,
#             "owned_by": "google",
#         },
#         {
#             "id": "gemini-1.5-pro-002",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4-0613",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {"id": "glm-4", "object": "model", "created": 1753286400, "owned_by": "z.ai"},
#         {
#             "id": "gpt-3.5-turbo-1106",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4-turbo-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-4-maverick",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwq-32b-preview:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "sonar-pro",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "tts-1-1106",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "minimax-m2.1",
#             "object": "model",
#             "created": 1766419200,
#             "owned_by": "minimax",
#         },
#         {
#             "id": "command",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-max-2026-01-23",
#             "object": "model",
#             "created": 1769356800,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "deepseek-v3.2-speciale",
#             "object": "model",
#             "created": 1764518400,
#             "owned_by": "deepseek",
#         },
#         {
#             "id": "jina-embeddings-v4",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "jinaai",
#         },
#         {
#             "id": "claude-opus-4-20250514",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "claude-opus-4-20250514-thinking",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "veo3-pro-frames",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-3.1-flash-image-preview",
#             "object": "model",
#             "created": 1772035200,
#             "owned_by": "google",
#         },
#         {"id": "grok-4.2", "object": "model", "created": 1772208000, "owned_by": "xai"},
#         {
#             "id": "gemini-2.0-flash-exp-image",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "google",
#         },
#         {
#             "id": "deepseek-v3.2",
#             "object": "model",
#             "created": 1764518400,
#             "owned_by": "deepseek",
#         },
#         {
#             "id": "chatgpt-4o-latest",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "deepseek-r1-searching",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4o-audio-preview-2024-12-17",
#             "object": "model",
#             "created": 1734364800,
#             "owned_by": "openai",
#         },
#         {
#             "id": "seed-1.6",
#             "object": "model",
#             "created": 1766481480,
#             "owned_by": "bytedance",
#         },
#         {
#             "id": "mistral-small-creative",
#             "object": "model",
#             "created": 1765814400,
#             "owned_by": "mistralai",
#         },
#         {
#             "id": "devstral-2512",
#             "object": "model",
#             "created": 1765209600,
#             "owned_by": "mistralai",
#         },
#         {
#             "id": "gpt-4-32k-0314",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.1-8b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "minimax-m2.5-lightning",
#             "object": "model",
#             "created": 1770825600,
#             "owned_by": "minimax",
#         },
#         {
#             "id": "glm-4.5-air",
#             "object": "model",
#             "created": 1753372800,
#             "owned_by": "z.ai",
#         },
#         {
#             "id": "deepseek-v3.1-base",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "Qwen/Qwen3-Reranker-4B",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-2.5-pro",
#             "object": "model",
#             "created": 1750089600,
#             "owned_by": "google",
#         },
#         {
#             "id": "magistral-medium-2506",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-coder-480b-a35b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-coder-next",
#             "object": "model",
#             "created": 1769788800,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "gemini-2.5-pro-preview-03-25",
#             "object": "model",
#             "created": 1742832000,
#             "owned_by": "google",
#         },
#         {
#             "id": "gpt-5.2-codex",
#             "object": "model",
#             "created": 1765987200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "ERNIE-Lite-8K-0922",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.3-70b-instruct:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "mistral-7b-instruct:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen2.5-vl-72b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "sora-2-hd",
#             "object": "model",
#             "created": 1759161600,
#             "owned_by": "openai",
#         },
#         {
#             "id": "command-r-plus",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-2.0-flash-thinking-exp-1219",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-image-1",
#             "object": "model",
#             "created": 1742832000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "olmo-3-7b-think",
#             "object": "model",
#             "created": 1763654400,
#             "owned_by": "allenai",
#         },
#         {
#             "id": "grok-3-reasoning",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "whisper-1",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-2.5-flash-deepsearch",
#             "object": "model",
#             "created": 1750089600,
#             "owned_by": "google",
#         },
#         {
#             "id": "grok-3-image",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "xai",
#         },
#         {
#             "id": "command-r7b-12-2024",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "deepseek-r1-distill-llama-70b:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ERNIE-4.0-8K",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-1.5-pro-latest",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-1.7b:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4o-mini-audio-preview",
#             "object": "model",
#             "created": 1756656000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gpt-oss-120b",
#             "object": "model",
#             "created": 1754323200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "text-embedding-3-large",
#             "object": "model",
#             "created": 1706112000,
#             "owned_by": "openai",
#         },
#         {"id": "glm-4.7", "object": "model", "created": 1766332800, "owned_by": "z.ai"},
#         {
#             "id": "qwen3-vl-32b-instruct",
#             "object": "model",
#             "created": 1761148800,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "deepseek-r1-distill-qwen-14b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ERNIE-Lite-8K-0308",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.1-sonar-small-128k-chat",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4o-image",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gpt-5.1-codex-high",
#             "object": "model",
#             "created": 1762963200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gemma-3-4b-it:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "minimax-m1:extended",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-max-thinking",
#             "object": "model",
#             "created": 1770566400,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "olmo-3-7b-instruct",
#             "object": "model",
#             "created": 1763654400,
#             "owned_by": "allenai",
#         },
#         {
#             "id": "ernie-4.5-turbo-128k-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.1-70b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-3-flash-preview",
#             "object": "model",
#             "created": 1765900800,
#             "owned_by": "google",
#         },
#         {
#             "id": "deepseek-prover-v2:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "deepseek-r1t2-chimera",
#             "object": "model",
#             "created": 1751904000,
#             "owned_by": "tngtech",
#         },
#         {
#             "id": "gpt-4",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "mistral-small-3.2-24b-instruct:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5-codex",
#             "object": "model",
#             "created": 1758556800,
#             "owned_by": "openai",
#         },
#         {
#             "id": "claude-sonnet-4-20250514-thinking",
#             "object": "model",
#             "created": 1747843200,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "seed-1.6-flash",
#             "object": "model",
#             "created": 1766481480,
#             "owned_by": "bytedance",
#         },
#         {
#             "id": "grok-4.1-thinking",
#             "object": "model",
#             "created": 1751990400,
#             "owned_by": "xai",
#         },
#         {
#             "id": "gemma-3-1b-it",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "grok-2-vision-1212",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ernie-x1-turbo-32k-preview",
#             "object": "model",
#             "created": 1748707200,
#             "owned_by": "baidu",
#         },
#         {
#             "id": "command-r-08-2024",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "deepseek-r1-distill-llama-8b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "deepseek-v3-base",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-14b:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-8b:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "sora-2-landscape",
#             "object": "model",
#             "created": 1759161600,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gemini-2.0-flash-lite-001",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.2-11b-vision-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.3-70b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "veo3-fast",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "molmo-2-8b:free",
#             "object": "model",
#             "created": 1767888000,
#             "owned_by": "allenai",
#         },
#         {
#             "id": "gpt-5-nano-2025-08-07",
#             "object": "model",
#             "created": 1754496000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "claude-opus-4-5-20251101",
#             "object": "model",
#             "created": 1763913600,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "nova-pro-v1",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5.3-codex-spark",
#             "object": "model",
#             "created": 1772726400,
#             "owned_by": "openai",
#         },
#         {
#             "id": "tng-r1t-chimera:free",
#             "object": "model",
#             "created": 1764086400,
#             "owned_by": "tngtech",
#         },
#         {
#             "id": "ernie-4.5-300b-a47b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "jina-embeddings-v2-base-code",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "mistral-small-24b-instruct-2501:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-2.5-pro-preview-05-06",
#             "object": "model",
#             "created": 1750089600,
#             "owned_by": "google",
#         },
#         {
#             "id": "o4-mini-deep-research",
#             "object": "model",
#             "created": 1760025600,
#             "owned_by": "openai",
#         },
#         {
#             "id": "ernie-4.5-turbo-vl-32k",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "olympiccoder-7b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "sonar-deep-research",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {"id": "glm-5", "object": "model", "created": 1770739200, "owned_by": "z.ai"},
#         {
#             "id": "gpt-5-codex-high",
#             "object": "model",
#             "created": 1758556800,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gpt-5.1-low",
#             "object": "model",
#             "created": 1762963200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gpt-4.1-nano",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4o-mini-search-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-32b:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "glm-4.5-air:free",
#             "object": "model",
#             "created": 1753372800,
#             "owned_by": "z.ai",
#         },
#         {
#             "id": "llama-3.2-11b-vision-instruct:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5-search-api-2025-10-14",
#             "object": "model",
#             "created": 1760371200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "claude-sonnet-4.5-20250929-thinking",
#             "object": "model",
#             "created": 1759075200,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "ernie-4.5-turbo-vl-32k-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-2.0-flash-thinking-exp",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-3.5-turbo-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "phi-4-multimodal-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "sonar-reasoning-pro",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "claude-3.7-sonnet",
#             "object": "model",
#             "created": 1740326400,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "grok-4.1-fast",
#             "object": "model",
#             "created": 1763481600,
#             "owned_by": "xai",
#         },
#         {
#             "id": "llama-3.3-nemotron-super-49b-v1.5",
#             "object": "model",
#             "created": 1760025600,
#             "owned_by": "nvidia",
#         },
#         {
#             "id": "deepseek-v3.2-exp",
#             "object": "model",
#             "created": 1759075200,
#             "owned_by": "deepseek",
#         },
#         {
#             "id": "gemini-3-pro-image-preview",
#             "object": "model",
#             "created": 1763568000,
#             "owned_by": "google",
#         },
#         {
#             "id": "gemini-1.5-flash-exp-0827",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4o-mini",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.1-405b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "nova-micro-v1",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "glm-4.7-thinking",
#             "object": "model",
#             "created": 1766418480,
#             "owned_by": "z.ai",
#         },
#         {
#             "id": "qwq-32b-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ministral-8b-2512",
#             "object": "model",
#             "created": 1764604800,
#             "owned_by": "mistralai",
#         },
#         {
#             "id": "glm-4.6-thinking",
#             "object": "model",
#             "created": 1759161600,
#             "owned_by": "z.ai",
#         },
#         {
#             "id": "gpt-4-1106-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "o1-mini-2024-09-12",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5-codex-medium",
#             "object": "model",
#             "created": 1758556800,
#             "owned_by": "openai",
#         },
#         {
#             "id": "nemotron-nano-12b-v2-vl:free",
#             "object": "model",
#             "created": 1761580800,
#             "owned_by": "nvidia",
#         },
#         {
#             "id": "grok-4-fast",
#             "object": "model",
#             "created": 1758211200,
#             "owned_by": "xai",
#         },
#         {
#             "id": "deepseek-v3",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "minimax-m1",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "mistral-medium-3",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5.4-pro",
#             "object": "model",
#             "created": 1772640000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gemini-2.5-flash-lite",
#             "object": "model",
#             "created": 1753113600,
#             "owned_by": "google",
#         },
#         {
#             "id": "claude-haiku-4.5",
#             "object": "model",
#             "created": 1760457600,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "gpt-3.5-turbo-16k",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "grok-2-1212",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3.5-flash-02-23",
#             "object": "model",
#             "created": 1771948800,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "mistral-embed-2312",
#             "object": "model",
#             "created": 1761840000,
#             "owned_by": "mistralai",
#         },
#         {
#             "id": "sora-2-pro",
#             "object": "model",
#             "created": 1759161600,
#             "owned_by": "openai",
#         },
#         {
#             "id": "pixtral-12b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-32b",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5.3-codex-xhigh",
#             "object": "model",
#             "created": 1770307200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "veo3.1-fast",
#             "object": "model",
#             "created": 1768406400,
#             "owned_by": "google",
#         },
#         {
#             "id": "deepseek-r1t-chimera",
#             "object": "model",
#             "created": 1756224000,
#             "owned_by": "tngtech",
#         },
#         {
#             "id": "deepseek-r1",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "deepseek-r1-0528-qwen3-8b:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-4-32k",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "o1-mini",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "ministral-3b-2512",
#             "object": "model",
#             "created": 1764604800,
#             "owned_by": "mistralai",
#         },
#         {
#             "id": "qwen3-next-80b-a3b-thinking",
#             "object": "model",
#             "created": 1757520000,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "nemotron-3-nano-30b-a3b:free",
#             "object": "model",
#             "created": 1765641600,
#             "owned_by": "nvidia",
#         },
#         {
#             "id": "deepseek-r1-zero",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "grok-vision-beta",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "moonshot-v1-32k",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "veo3-pro",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3.5-plus-02-15",
#             "object": "model",
#             "created": 1771171200,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "gpt-5.2-pro",
#             "object": "model",
#             "created": 1765296000,
#             "owned_by": "openai",
#         },
#         {
#             "id": "minimax-m2.5",
#             "object": "model",
#             "created": 1770825600,
#             "owned_by": "minimax",
#         },
#         {
#             "id": "gpt-5.3-codex",
#             "object": "model",
#             "created": 1770307200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "glm-4.7-flash",
#             "object": "model",
#             "created": 1768752000,
#             "owned_by": "z.ai",
#         },
#         {
#             "id": "olmo-3.1-32b-instruct",
#             "object": "model",
#             "created": 1767628800,
#             "owned_by": "allenai",
#         },
#         {
#             "id": "qwen-plus-2025-07-28:thinking",
#             "object": "model",
#             "created": 1757260800,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "glm-4.5-x",
#             "object": "model",
#             "created": 1753372800,
#             "owned_by": "z.ai",
#         },
#         {
#             "id": "devstral-medium",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.1-nemotron-nano-8b-v1:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-image-1.5",
#             "object": "model",
#             "created": 1765814400,
#             "owned_by": "openai",
#         },
#         {
#             "id": "qwen-vl-max",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen2.5-vl-3b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "deepseek-ocr",
#             "object": "model",
#             "created": 1760889600,
#             "owned_by": "deepseek",
#         },
#         {
#             "id": "mistral-small-3.1-24b-instruct:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-2.5-flash-lite-preview-06-17",
#             "object": "model",
#             "created": 1750089600,
#             "owned_by": "google",
#         },
#         {
#             "id": "llama-3.3-nemotron-super-49b-v1",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "magistral-small-2506",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5-codex-low",
#             "object": "model",
#             "created": 1758556800,
#             "owned_by": "openai",
#         },
#         {
#             "id": "gpt-4.5-preview",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "nova-lite-v1",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen-2-vl-72b-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gpt-5.3-codex-medium",
#             "object": "model",
#             "created": 1770307200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "qwen3-vl-235b-a22b-thinking",
#             "object": "model",
#             "created": 1758556800,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "gemini-2.0-flash-exp:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "grok-beta",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-235b-a22b:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "qwen3-next-80b-a3b-instruct",
#             "object": "model",
#             "created": 1757520000,
#             "owned_by": "alibaba",
#         },
#         {
#             "id": "gemini-2.5-pro-exp-03-25",
#             "object": "model",
#             "created": 1742832000,
#             "owned_by": "google",
#         },
#         {
#             "id": "phi-3.5-mini-128k-instruct",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-2.5-pro-preview-06-05",
#             "object": "model",
#             "created": 1750089600,
#             "owned_by": "google",
#         },
#         {
#             "id": "jina-embeddings-v3",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "jinaai",
#         },
#         {"id": "glm-4.6", "object": "model", "created": 1759161600, "owned_by": "z.ai"},
#         {
#             "id": "ministral-14b-2512",
#             "object": "model",
#             "created": 1764604800,
#             "owned_by": "mistralai",
#         },
#         {
#             "id": "claude-3-haiku-20240307",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-pro-1.5-exp-0801",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-3.1-8b-instruct:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "llama-4-scout",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "claude-haiku-4.5-thinking",
#             "object": "model",
#             "created": 1760457600,
#             "owned_by": "anthropic",
#         },
#         {
#             "id": "gemma-3n-e2b-it:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "phi-4-reasoning:free",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "gemini-2.5-flash-preview-05-20",
#             "object": "model",
#             "created": 1747670400,
#             "owned_by": "google",
#         },
#         {
#             "id": "gpt-5.1-codex-medium",
#             "object": "model",
#             "created": 1762963200,
#             "owned_by": "openai",
#         },
#         {
#             "id": "mistral-saba",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#         {
#             "id": "tts-1-hd",
#             "object": "model",
#             "created": 1723766400,
#             "owned_by": "apertis",
#         },
#     ],
# }
