"""
This type stub file was generated by pyright.
"""

import sys
import ctypes
import glob
import os
from importlib.resources import files
from ctranslate2._ext import AsyncGenerationResult, AsyncScoringResult, AsyncTranslationResult, DataType, Device, Encoder, EncoderForwardOutput, ExecutionStats, GenerationResult, GenerationStepResult, Generator, MpiInfo, ScoringResult, StorageView, TranslationResult, Translator, contains_model, get_cuda_device_count, get_supported_compute_types, set_random_seed
from ctranslate2.extensions import register_extensions
from ctranslate2.logging import get_log_level, set_log_level
from ctranslate2 import converters, models, specs
from ctranslate2.version import __version__

if sys.platform == "win32":
    module_name = ...
    package_dir = ...
