"""
This type stub file was generated by pyright.
"""

_PYTHON_TO_CT2_LEVEL = ...
_CT2_TO_PYTHON_LEVEL = ...
def set_log_level(level: int): # -> None:
    """Sets the CTranslate2 logging level from a Python logging level.

    Arguments:
      level: A Python logging level.

    Example:

        >>> import logging
        >>> ctranslate2.set_log_level(logging.INFO)

    Note:
       The argument is a Python logging level for convenience, but this function
       controls the C++ logs of the library.
    """
    ...

def get_log_level() -> int:
    """Returns the current logging level.

    Returns:
      A Python logging level.
    """
    ...

